### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ferambot**
Hi, I am Feram,

I'm a bot and I work on behalf of [my team][feramhq].

If my merge request helped to improve this repository,
please consider to [star my repo][repo] to show some love! 😊

If I didn't behave, you can [create an issue][issues]
and my parents will try to fix me.

Love, hugs and kisses,
your [Feram][feram]

PS:
I'm currently getting upgraded with some amazing
new features. Stay up to date by signing up for
the newsletter on [feram.co] or by following me on [Twitter].

[feramhq]: https://github.com/feramhq
[feram]: https://github.com/ferambot
[repo]: https://github.com/feramhq/feram
[issues]: https://github.com/feramhq/feram/issues
[feram.co]: http://feram.co
[Twitter]: https://twitter.com/ferambot

### CODE REVIEW

**Comment by manumena** [comment]
Y esto?

**Comment by kevinfra** [comment]
Aparentemente es un bot que "ayuda" a otros repos abiertos y luego de hacer
los cambios hace un pull request. En nuestro caso, lo ùnico que hizo fue
hacer cambios de "ortografìa" o "gramatica" (no me acuerdo) y resultò ser
que puso una doble "m" en una palabra que la diferencia en ingles y en
castellano es eso. Así que lo descarté

**Comment by adius** [comment]
Sorry for the unhelpful pull request. There is already an issue for this: https://github.com/feramhq/feram/issues/23

**Comment by manumena** [comment]
@adius Nice project!

**Pull request closed without merging**
